apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-kuber-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: azure-kuber-demo
  template:
    metadata:
      labels:
        app: azure-kuber-demo
    spec:
      containers:
        - name: azure-kuber-demo
          image: firstprojcregistry.azurecr.io/demos/azure-kuber-demo
          ports:
            - containerPort: 8080