apiVersion: v1
kind: Service
metadata:
  name: azure-kuber-demo
  labels:
    name: azure-kuber-demo
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: azure-kuber-demo
  type: LoadBalancer